---
title: "extraInserts"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Description

The purpose of this trival package is to offer a set of conveniance functions inserting various pipes and operators so those can be conveniently linked to keyboard shortcuts in RStudio.

### Available operators

| Operator      | Notes                                                         |
| ------------- | ------------------------------------------------------------- |
| **`->`**      | [Rightwards form of common assignment operator][1]            |
| **`%<>%`**    | Pipe operators offered in the excellent [magrittr][2] package |

## Installation

```{r installation, eval=FALSE, echo=TRUE}
if (!requireNamespace("devtools", quietly = TRUE))
  install.packages("devtools")
devtools::install_github('konradedgar/extraInserts')
```

[1]: https://stat.ethz.ch/R-manual/R-devel/library/base/html/assignOps.html
[2]: https://cran.r-project.org/web/packages/magrittr/vignettes/magrittr.html 
